// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiiOVzczqSgXUC28BEuMcIy_3hFd9IJj0',
    appId: '1:74291779477:android:35f432ca6933f78cb7889c',
    messagingSenderId: '74291779477',
    projectId: 'friendly-20929',
    databaseURL: 'https://friendly-20929-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'friendly-20929.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAk-_9LxpxWdWWvlldASlNu9HndT3dtN4',
    appId: '1:74291779477:ios:633b85a057d561bdb7889c',
    messagingSenderId: '74291779477',
    projectId: 'friendly-20929',
    databaseURL: 'https://friendly-20929-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'friendly-20929.appspot.com',
    iosClientId: '74291779477-7qkr4kh29kr8c8rk5hel7vi2h3mvfo28.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );
}
